# Generated by Django 4.2.19 on 2025-03-13 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cname", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="Condition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("conditionname", models.CharField(max_length=10)),
                ("conditionurl", models.ImageField(upload_to="conditions/")),
            ],
        ),
        migrations.CreateModel(
            name="Goods",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gname", models.CharField(max_length=100, unique=True)),
                ("gdesc", models.CharField(max_length=100)),
                ("oldprice", models.DecimalField(decimal_places=2, max_digits=5)),
                ("price", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="goodsapp.category",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GoodsDetailName",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gdname", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="Weight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("wname", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="Inventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("count", models.PositiveIntegerField(default=100)),
                (
                    "condition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="goodsapp.condition",
                    ),
                ),
                (
                    "goods",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="goodsapp.goods"
                    ),
                ),
                (
                    "weight",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="goodsapp.weight",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GoodDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gdurl", models.ImageField(upload_to="")),
                (
                    "goods",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="goodsapp.goods"
                    ),
                ),
                (
                    "goodsdname",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="goodsapp.goodsdetailname",
                    ),
                ),
            ],
        ),
    ]
